export const realProducts = [
    // HEADPHONES (21)
    { name: "Sony WH-1000XM5", brand: "Sony", cat: "Headphones", price: 31990, sku: "AUR-HP-0001", short: "Industry-leading noise canceling wireless headphones." },
    { name: "Sennheiser HD 800 S", brand: "Sennheiser", cat: "Headphones", price: 149990, sku: "AUR-HP-0002", short: "Reference-class audiophile open-back headphones." },
    { name: "Sennheiser HD 600", brand: "Sennheiser", cat: "Headphones", price: 34990, sku: "AUR-HP-0003", short: "Audiophile open dynamic hi-fi professional headphones." },
    { name: "Sennheiser Momentum 4 Wireless", brand: "Sennheiser", cat: "Headphones", price: 29990, sku: "AUR-HP-0004", short: "Premium wireless headphones with adaptive ANC." },
    { name: "Bose QuietComfort Ultra", brand: "Bose", cat: "Headphones", price: 35900, sku: "AUR-HP-0005", short: "World-class noise cancellation with immersive spatial audio." },
    { name: "Apple AirPods Max", brand: "Apple", cat: "Headphones", price: 59900, sku: "AUR-HP-0006", short: "High-fidelity audio with active noise cancellation." },
    { name: "Audio-Technica ATH-M50x", brand: "Audio-Technica", cat: "Headphones", price: 12999, sku: "AUR-HP-0007", short: "Professional studio monitor headphones." },
    { name: "Audio-Technica ATH-M40x", brand: "Audio-Technica", cat: "Headphones", price: 8999, sku: "AUR-HP-0008", short: "Flat-tuned professional monitor headphones." },
    { name: "Beyerdynamic DT 770 PRO", brand: "Beyerdynamic", cat: "Headphones", price: 13999, sku: "AUR-HP-0009", short: "Closed-back studio headphones for mixing." },
    { name: "Beyerdynamic DT 990 PRO", brand: "Beyerdynamic", cat: "Headphones", price: 14499, sku: "AUR-HP-0010", short: "Open-back studio headphones for spacious sound." },
    { name: "Focal Utopia", brand: "Focal", cat: "Headphones", price: 399999, sku: "AUR-HP-0011", short: "Ultimate high-fidelity open-back reference headphones." },
    { name: "Focal Clear Mg", brand: "Focal", cat: "Headphones", price: 139990, sku: "AUR-HP-0012", short: "High-end open-back headphones with magnesium dome." },
    { name: "Meze Empyrean II", brand: "Meze Audio", cat: "Headphones", price: 279999, sku: "AUR-HP-0013", short: "Isodynamic hybrid array open-back headphones." },
    { name: "Audeze LCD-X", brand: "Audeze", cat: "Headphones", price: 119990, sku: "AUR-HP-0014", short: "Planar magnetic reference headphones." },
    { name: "Audeze LCD-5", brand: "Audeze", cat: "Headphones", price: 429990, sku: "AUR-HP-0015", short: "Flagship planar magnetic open-back headphones." },
    { name: "HiFiMAN Arya Stealth", brand: "HiFiMAN", cat: "Headphones", price: 129999, sku: "AUR-HP-0016", short: "Planar magnetic headphones with stealth magnets." },
    { name: "HiFiMAN Sundara", brand: "HiFiMAN", cat: "Headphones", price: 24999, sku: "AUR-HP-0017", short: "Planar magnetic open-back audiophile headphones." },
    { name: "Shure SRH1540", brand: "Shure", cat: "Headphones", price: 49990, sku: "AUR-HP-0018", short: "Premium closed-back headphones for audiophiles." },
    { name: "AKG K361", brand: "AKG", cat: "Headphones", price: 7999, sku: "AUR-HP-0019", short: "Over-ear closed-back studio headphones." },
    { name: "AKG K702", brand: "AKG", cat: "Headphones", price: 17990, sku: "AUR-HP-0020", short: "Reference open-back studio headphones." },
    { name: "Philips Fidelio X2HR", brand: "Philips", cat: "Headphones", price: 14999, sku: "AUR-HP-0021", short: "High resolution open-air audio headphones." },

    // EARPHONES / IEM (19)
    { name: "Moondrop Aria", brand: "Moondrop", cat: "Earphones", price: 6999, sku: "AUR-IEM-0001", short: "High-performance LCP diaphragm dynamic IEM." },
    { name: "Moondrop Blessing 3", brand: "Moondrop", cat: "Earphones", price: 28990, sku: "AUR-IEM-0002", short: "Hybrid 2DD + 4BA in-ear monitors." },
    { name: "Moondrop Chu II", brand: "Moondrop", cat: "Earphones", price: 1999, sku: "AUR-IEM-0003", short: "Budget dynamic driver in-ear monitors." },
    { name: "7Hz Timeless", brand: "7Hz", cat: "Earphones", price: 19990, sku: "AUR-IEM-0004", short: "14.2mm planar magnetic in-ear monitors." },
    { name: "Sennheiser IE 200", brand: "Sennheiser", cat: "Earphones", price: 12990, sku: "AUR-IEM-0005", short: "Audiophile in-ear monitors with TrueResponse." },
    { name: "Sennheiser IE 600", brand: "Sennheiser", cat: "Earphones", price: 59990, sku: "AUR-IEM-0006", short: "Exceptional detail with ZR01 amorphous zirconium housing." },
    { name: "Sennheiser IE 900", brand: "Sennheiser", cat: "Earphones", price: 119990, sku: "AUR-IEM-0007", short: "Flagship audiophile in-ear monitors with X3R technology." },
    { name: "Shure SE215", brand: "Shure", cat: "Earphones", price: 9999, sku: "AUR-IEM-0008", short: "Sound isolating earphones with dynamic microdriver." },
    { name: "Shure SE846", brand: "Shure", cat: "Earphones", price: 89990, sku: "AUR-IEM-0009", short: "Quad high-definition microdrivers for extended clarity." },
    { name: "Campfire Audio Andromeda", brand: "Campfire Audio", cat: "Earphones", price: 99990, sku: "AUR-IEM-0010", short: "Five balanced armature in-ear monitors." },
    { name: "Campfire Audio Solaris", brand: "Campfire Audio", cat: "Earphones", price: 139990, sku: "AUR-IEM-0011", short: "Stellar horizon hybrid in-ear monitors." },
    { name: "Thieaudio Monarch MKII", brand: "Thieaudio", cat: "Earphones", price: 89999, sku: "AUR-IEM-0012", short: "Tribrid in-ear monitors with electrostatic drivers." },
    { name: "Truthear x Crinacle Zero", brand: "Truthear", cat: "Earphones", price: 4499, sku: "AUR-IEM-0013", short: "Dual dynamic driver in-ear monitors tuned by Crinacle." },
    { name: "KZ ZS10 Pro", brand: "KZ", cat: "Earphones", price: 3499, sku: "AUR-IEM-0014", short: "4BA+1DD hybrid driver in-ear monitors." },
    { name: "FiiO FH3", brand: "FiiO", cat: "Earphones", price: 11990, sku: "AUR-IEM-0015", short: "Triple driver hybrid in-ear monitors." },
    { name: "FiiO FD5", brand: "FiiO", cat: "Earphones", price: 27990, sku: "AUR-IEM-0016", short: "Dynamic driver flagship in-ear monitors." },
    { name: "Meze Rai Penta", brand: "Meze Audio", cat: "Earphones", price: 99999, sku: "AUR-IEM-0017", short: "Penta hybrid driver in-ear monitors." },
    { name: "Sony IER-Z1R", brand: "Sony", cat: "Earphones", price: 139990, sku: "AUR-IEM-0018", short: "Signature series in-ear headphones." },
    { name: "Etymotic ER4SR", brand: "Etymotic", cat: "Earphones", price: 24990, sku: "AUR-IEM-0019", short: "Studio reference precision matched earphones." },

    // TRUE WIRELESS / TWS (15)
    { name: "Sony WF-1000XM5", brand: "Sony", cat: "True Wireless", price: 24990, sku: "AUR-TWS-0001", short: "The best truly wireless noise canceling earbuds." },
    { name: "Apple AirPods Pro (2nd Gen)", brand: "Apple", cat: "True Wireless", price: 24900, sku: "AUR-TWS-0002", short: "Active noise cancellation and adaptive audio." },
    { name: "Sennheiser Momentum True Wireless 3", brand: "Sennheiser", cat: "True Wireless", price: 19990, sku: "AUR-TWS-0003", short: "High-fidelity wireless earbuds with ANC." },
    { name: "Bose QuietComfort Earbuds II", brand: "Bose", cat: "True Wireless", price: 25900, sku: "AUR-TWS-0004", short: "Personalized noise cancellation and sound." },
    { name: "Samsung Galaxy Buds2 Pro", brand: "Samsung", cat: "True Wireless", price: 15999, sku: "AUR-TWS-0005", short: "24-bit Hi-Fi audio with intelligent ANC." },
    { name: "Jabra Elite 8 Active", brand: "Jabra", cat: "True Wireless", price: 17999, sku: "AUR-TWS-0006", short: "The world's toughest active earbuds." },
    { name: "Jabra Elite 10", brand: "Jabra", cat: "True Wireless", price: 22999, sku: "AUR-TWS-0007", short: "Advanced comfort and Dolby Atmos sound." },
    { name: "Beats Fit Pro", brand: "Beats", cat: "True Wireless", price: 19900, sku: "AUR-TWS-0008", short: "True wireless noise cancelling earbuds." },
    { name: "Anker Soundcore Liberty 4", brand: "Anker", cat: "True Wireless", price: 11999, sku: "AUR-TWS-0009", short: "Crisp spatial audio and heart rate tracking." },
    { name: "EarFun Air Pro 3", brand: "EarFun", cat: "True Wireless", price: 5999, sku: "AUR-TWS-0010", short: "LE Audio ANC true wireless earbuds." },
    { name: "Sony LinkBuds S", brand: "Sony", cat: "True Wireless", price: 12990, sku: "AUR-TWS-0011", short: "Never off, ultra-lightweight noise canceling earbuds." },
    { name: "Cambridge Audio Melomania 1+", brand: "Cambridge Audio", cat: "True Wireless", price: 9999, sku: "AUR-TWS-0012", short: "Incredible sound, enhanced app control." },
    { name: "Nothing Ear (2)", brand: "Nothing", cat: "True Wireless", price: 9999, sku: "AUR-TWS-0013", short: "Hi-Res Audio certified with personalized ANC." },
    { name: "Technics EAH-AZ80", brand: "Technics", cat: "True Wireless", price: 27990, sku: "AUR-TWS-0014", short: "Premium hi-fi true wireless earbuds." },
    { name: "Bowers & Wilkins Pi7 S2", brand: "Bowers & Wilkins", cat: "True Wireless", price: 34990, sku: "AUR-TWS-0015", short: "True 24-bit audio connection with ANC." },

    // SPEAKERS (19)
    { name: "KEF LS50 Wireless II", brand: "KEF", cat: "Speakers", price: 249990, sku: "AUR-SPK-0001", short: "The ultimate wireless hifi system." },
    { name: "KEF Q350", brand: "KEF", cat: "Speakers", price: 64990, sku: "AUR-SPK-0002", short: "Bookshelf speakers with Uni-Q array." },
    { name: "Sony SRS-XB13", brand: "Sony", cat: "Speakers", price: 3990, sku: "AUR-SPK-0003", short: "Extra bass portable wireless speaker." },
    { name: "Sony SRS-XG300", brand: "Sony", cat: "Speakers", price: 22990, sku: "AUR-SPK-0004", short: "X-Series portable wireless speaker." },
    { name: "JBL Charge 5", brand: "JBL", cat: "Speakers", price: 14999, sku: "AUR-SPK-0005", short: "Portable waterproof speaker with powerbank." },
    { name: "JBL Flip 6", brand: "JBL", cat: "Speakers", price: 10999, sku: "AUR-SPK-0006", short: "Portable waterproof bluetooth speaker." },
    { name: "Marshall Stanmore III", brand: "Marshall", cat: "Speakers", price: 34999, sku: "AUR-SPK-0007", short: "Classic Marshall design home bluetooth speaker." },
    { name: "Marshall Emberton II", brand: "Marshall", cat: "Speakers", price: 14999, sku: "AUR-SPK-0008", short: "Compact portable bluetooth speaker." },
    { name: "Sonos Era 100", brand: "Sonos", cat: "Speakers", price: 27999, sku: "AUR-SPK-0009", short: "Next-gen smart speaker with room-filling sound." },
    { name: "Sonos Era 300", brand: "Sonos", cat: "Speakers", price: 49999, sku: "AUR-SPK-0010", short: "Premium smart speaker with spatial audio." },
    { name: "Sonos Roam", brand: "Sonos", cat: "Speakers", price: 18999, sku: "AUR-SPK-0011", short: "Portable waterproof smart speaker." },
    { name: "Edifier R1280T", brand: "Edifier", cat: "Speakers", price: 9999, sku: "AUR-SPK-0012", short: "Powered bookshelf speakers." },
    { name: "Edifier S2000MKIII", brand: "Edifier", cat: "Speakers", price: 39999, sku: "AUR-SPK-0013", short: "Audiophile active bookshelf speakers." },
    { name: "Audioengine A2+", brand: "Audioengine", cat: "Speakers", price: 24990, sku: "AUR-SPK-0014", short: "Wireless desktop computer speakers." },
    { name: "Audioengine A5+", brand: "Audioengine", cat: "Speakers", price: 44990, sku: "AUR-SPK-0015", short: "Premium powered bookshelf speakers." },
    { name: "Klipsch R-51M", brand: "Klipsch", cat: "Speakers", price: 26990, sku: "AUR-SPK-0016", short: "Reference series bookshelf speakers." },
    { name: "Klipsch The Fives", brand: "Klipsch", cat: "Speakers", price: 79990, sku: "AUR-SPK-0017", short: "Powered monitor speakers with HDMI-ARC." },
    { name: "Bowers & Wilkins Zeppelin", brand: "Bowers & Wilkins", cat: "Speakers", price: 69990, sku: "AUR-SPK-0018", short: "Wireless smart speaker." },
    { name: "Ultimate Ears BOOM 3", brand: "Ultimate Ears", cat: "Speakers", price: 12999, sku: "AUR-SPK-0019", short: "Portable waterproof bluetooth speaker." },

    // MICROPHONES (14)
    { name: "Shure SM7B", brand: "Shure", cat: "Microphones", price: 38990, sku: "AUR-MIC-0001", short: "Legendary vocal microphone." },
    { name: "Shure SM58", brand: "Shure", cat: "Microphones", price: 9990, sku: "AUR-MIC-0002", short: "Industry standard vocal microphone." },
    { name: "RODE NT1-A", brand: "RODE", cat: "Microphones", price: 19999, sku: "AUR-MIC-0003", short: "Large-diaphragm cardioid condenser microphone." },
    { name: "RODE PodMic", brand: "RODE", cat: "Microphones", price: 11499, sku: "AUR-MIC-0004", short: "Broadcast-grade dynamic microphone." },
    { name: "RODE Wireless GO II", brand: "RODE", cat: "Microphones", price: 27999, sku: "AUR-MIC-0005", short: "Dual channel wireless microphone system." },
    { name: "Blue Yeti", brand: "Blue", cat: "Microphones", price: 11999, sku: "AUR-MIC-0006", short: "Multi-pattern USB microphone." },
    { name: "Blue Snowball iCE", brand: "Blue", cat: "Microphones", price: 4499, sku: "AUR-MIC-0007", short: "Plug and play USB microphone." },
    { name: "Audio-Technica AT2020", brand: "Audio-Technica", cat: "Microphones", price: 8999, sku: "AUR-MIC-0008", short: "Cardioid condenser studio microphone." },
    { name: "Audio-Technica AT2020USB+", brand: "Audio-Technica", cat: "Microphones", price: 13999, sku: "AUR-MIC-0009", short: "Cardioid condenser USB microphone." },
    { name: "Elgato Wave:3", brand: "Elgato", cat: "Microphones", price: 14999, sku: "AUR-MIC-0010", short: "Premium USB condenser microphone and digital mixer." },
    { name: "HyperX QuadCast S", brand: "HyperX", cat: "Microphones", price: 13990, sku: "AUR-MIC-0011", short: "RGB USB condenser microphone." },
    { name: "Sennheiser MKH 416", brand: "Sennheiser", cat: "Microphones", price: 99990, sku: "AUR-MIC-0012", short: "Short shotgun interference tube microphone." },
    { name: "AKG Pro Audio C414", brand: "AKG", cat: "Microphones", price: 89990, sku: "AUR-MIC-0013", short: "Multi-pattern condenser microphone." },
    { name: "Neumann U87 Ai", brand: "Neumann", cat: "Microphones", price: 299990, sku: "AUR-MIC-0014", short: "Studio microphone standard." },

    // DAC / AMP / Interfaces (15)
    { name: "Focusrite Scarlett 2i2 (4th Gen)", brand: "Focusrite", cat: "DAC & Amplifiers", price: 18999, sku: "AUR-DAC-0001", short: "2-in, 2-out USB audio interface." },
    { name: "Universal Audio Apollo Twin X", brand: "Universal Audio", cat: "DAC & Amplifiers", price: 99990, sku: "AUR-DAC-0002", short: "Thunderbolt 3 audio interface with real-time UAD processing." },
    { name: "MOTU M2", brand: "MOTU", cat: "DAC & Amplifiers", price: 19999, sku: "AUR-DAC-0003", short: "2x2 USB-C audio interface." },
    { name: "Audient iD14 MKII", brand: "Audient", cat: "DAC & Amplifiers", price: 25999, sku: "AUR-DAC-0004", short: "10in/6out USB audio interface." },
    { name: "FiiO E10K", brand: "FiiO", cat: "DAC & Amplifiers", price: 5999, sku: "AUR-DAC-0005", short: "USB DAC and headphone amplifier." },
    { name: "FiiO K5 Pro ESS", brand: "FiiO", cat: "DAC & Amplifiers", price: 16999, sku: "AUR-DAC-0006", short: "Desktop DAC and headphone amplifier." },
    { name: "FiiO BTR7", brand: "FiiO", cat: "DAC & Amplifiers", price: 19999, sku: "AUR-DAC-0007", short: "Portable Bluetooth amplifier." },
    { name: "Chord Mojo 2", brand: "Chord Electronics", cat: "DAC & Amplifiers", price: 54990, sku: "AUR-DAC-0008", short: "Portable DAC and headphone amplifier." },
    { name: "Chord Hugo 2", brand: "Chord Electronics", cat: "DAC & Amplifiers", price: 224990, sku: "AUR-DAC-0009", short: "Transportable DAC and headphone amp." },
    { name: "iFi Zen DAC V2", brand: "iFi Audio", cat: "DAC & Amplifiers", price: 15999, sku: "AUR-DAC-0010", short: "High-resolution USB DAC and amp." },
    { name: "iFi hip-dac2", brand: "iFi Audio", cat: "DAC & Amplifiers", price: 16999, sku: "AUR-DAC-0011", short: "Portable high-res DAC/amp." },
    { name: "Topping DX3 Pro+", brand: "Topping", cat: "DAC & Amplifiers", price: 18999, sku: "AUR-DAC-0012", short: "Desktop DAC and headphone amplifier with Bluetooth." },
    { name: "Schiit Magni+", brand: "Schiit", cat: "DAC & Amplifiers", price: 12999, sku: "AUR-DAC-0013", short: "Discrete headphone amp and preamp." },
    { name: "Schiit Modi+", brand: "Schiit", cat: "DAC & Amplifiers", price: 12999, sku: "AUR-DAC-0014", short: "Affordable desktop DAC." },
    { name: "AudioQuest DragonFly Cobalt", brand: "AudioQuest", cat: "DAC & Amplifiers", price: 29990, sku: "AUR-DAC-0015", short: "USB DAC and headphone amp." },

    // ACCESSORIES (13)
    { name: "Sennheiser Headphone Stand", brand: "Sennheiser", cat: "Accessories", price: 3499, sku: "AUR-ACC-0001", short: "Glass holder for premium headphones." },
    { name: "FiiO LC-BT2", brand: "FiiO", cat: "Accessories", price: 6999, sku: "AUR-ACC-0002", short: "Bluetooth neckband cable for IEMs." },
    { name: "Audio-Technica AT-PEQ30", brand: "Audio-Technica", cat: "Accessories", price: 19999, sku: "AUR-ACC-0003", short: "Phono equalizer for turntables." },
    { name: "Geekria Headphone Case", brand: "Geekria", cat: "Accessories", price: 2499, sku: "AUR-ACC-0004", short: "Hard shell carrying case for large headphones." },
    { name: "SpinFit CP145", brand: "SpinFit", cat: "Accessories", price: 1299, sku: "AUR-ACC-0005", short: "Silicone ear tips for IEMs." },
    { name: "Comply Foam Tips", brand: "Comply", cat: "Accessories", price: 1999, sku: "AUR-ACC-0006", short: "Memory foam ear tips for isolation." },
    { name: "Shure RMCE-BT2", brand: "Shure", cat: "Accessories", price: 12999, sku: "AUR-ACC-0007", short: "High-resolution Bluetooth 5.0 earphone communication cable." },
    { name: "FiiO LF-RB Magnetic Cable", brand: "FiiO", cat: "Accessories", price: 4499, sku: "AUR-ACC-0008", short: "Magnetic audio cable for IEMs." },
    { name: "DDHiFi TC35B", brand: "DDHiFi", cat: "Accessories", price: 3999, sku: "AUR-ACC-0009", short: "USB-C to 3.5mm adapter." },
    { name: "AudioQuest Tower RCA Cable", brand: "AudioQuest", cat: "Accessories", price: 2999, sku: "AUR-ACC-0010", short: "High-quality analog audio interconnect." },
    { name: "UGREEN 3.5mm Aux Cable", brand: "UGREEN", cat: "Accessories", price: 499, sku: "AUR-ACC-0011", short: "Braided audio auxiliary cable." },
    { name: "Anker USB-C to 3.5mm Adapter", brand: "Anker", cat: "Accessories", price: 1499, sku: "AUR-ACC-0012", short: "Lossless audio adapter for modern smartphones." },
    { name: "Dekoni Choice Leather Earpads", brand: "Dekoni", cat: "Accessories", price: 4999, sku: "AUR-ACC-0013", short: "Premium replacement earpads for audiophile headphones." }
];
